repos:
  - repo: local
    hooks:
      - id: format
        name: ruff format
        description: "Format code with ruff"
        entry: make format
        language: system

      - id: check
        name: ruff check
        description: "Lint and fix with ruff"
        entry: make check
        language: system

      - id: mypy
        name: mypy
        description: "Type check with mypy"
        entry: make mypy
        language: system

      - id: vulture
        name: vulture
        description: "Find dead code with vulture"
        entry: make vulture
        language: system