services:
  web-server:
    container_name: web-server
    build:
      context: .
      dockerfile: ./WebServer/Dockerfile
    ports: ["8000:8000"]
    env_file:
      - ${ENV_FILE:-dev.env}
    restart: "on-failure:3" 

  ai-worker:
    container_name: ai-worker
    build:
      context: .
      dockerfile: ./AIWorker/Dockerfile
    ports: ["8001:8001"]
    env_file:
      - ${ENV_FILE:-dev.env}
    restart: "on-failure:3"


volumes:
  redis-data: